- pyproject.toml
I froze the dependencies to the latest one my python version installed.
> chore(dependencies): Freezing dependencies versions from core packages.

- src/infrasys/time_series_manager.py
- tests/test_system.py
The backtrace seen by a user that calls System.add_time_series with an incorrect argument order was confusing.
> Add a better error message

- src/infrasys/base_quantity.py
- src/infrasys/quantities.py
- src/infrasys/system.py
- src/infrasys/time_series_models.py
- tests/test_base_quantity.py
- tests/test_serialization.py
- I do like the simplicity of specifying the quantities as functions, but do not like the capital letter. Shall we instead follow a different  convention like `active_power`? Or shall I define them as classes with the caveat that it can not be in one liner.
List of changes:
- Removed `__new__` from BaseQuantity
- Added a  unit check to check dimensionality is correct,
- Added validate on `BaseQuantity` to perform pint validation on pydantic
- Added testing for BaseQuantity class and units.
Closes #24
> fix(pint_units): Fixed `BaseQuantity` to allow quantities multiplications

- src/infrasys/base_quantity.py
- tests/test_base_quantity.py
List of changes:
- Removed `str(input_value.magnitude)` to return a proper number instead of a string when calling `.model_dump()`
- Added a specific serialization option when calling `.model_dump(mode="json")` or `.model_dump_json()` to return a string version of the field. This is only import for pint quantities, such that it returns something like `10 kV` that is easily deserialized with pint,
- Added better type check for instances of the BaseQuantity used on the pydantic model,
- Relaxed the schema serialization since pint will handle most of it,
- Added better typehint for pydantic classmethods
> fix(base_quantity): Removed string return from serialization of pint quantity.

- docs/how_tos/save_system.md
- src/infrasys/system.py
- src/infrasys/time_series_metadata_store.py
- tests/test_serialization.py
List of changes:
- Created a new method `.save` that saves all the content of the system
(.json + time series) to a desired folder,
- Save method can archive the folder to enable easy sharing of the
system,
- Added testing to validate that save in fact creates the folder and
that when we zip it we delete that folder.
- Added `howto` section that explains the method.
Closes https://github.com/NREL/infrasys/issues/10
> feat(system): Added new method to save the system to a given folder.

- src/infrasys/function_data.py
- tests/test_function_data.py
Added new file (function_data.py) to include the function_data structs from InfrastructureSystems as python classes, which are necessary for parsing data for cost function inputs into Sienna. I included classes for linear and quadratic functions, as well as piecewise linear and piecewise step functions.
Note, we kept PiecewiseLinearData.points as a list of NamedTuples (rather than change it to two separate lists of x, y coordinates) to ensure it is consistent with the structs built on top of function_data in InfrastructureSystems and elsewhere.
> Add function_data classes from InfrastructureSystems

- src/infrasys/system.py
- src/infrasys/time_series_manager.py
- src/infrasys/time_series_metadata_store.py
- src/infrasys/utils/sqlite.py
- tests/test_arrow_storage.py
- tests/test_serialization.py
1. Move control over the database to the System instead of TimeSeriesMetadataStore. This will allow us to use the database for supplemental attributes.
2. Use SQL query params for user variables.
> Move database ownership to System

- docs/explanation/system.md
- src/infrasys/component_associations.py
- src/infrasys/component_manager.py
- src/infrasys/exceptions.py
- src/infrasys/system.py
- tests/test_system.py
> Store associations between components

- src/infrasys/component_manager.py
- tests/test_system.py
The old behavior was causing a problem for user code that passed a dynamically-built list of components to system.add_components. Requiring that code to check for an empty list was onerous, and we can safely let it go through with no error.
> Allow no components in add_components

- pyproject.toml
- src/infrasys/pint_quantities.py
- tests/test_pint_quantities.py
This was the original idea we intended before introducing `BaseQuantity`. It is more simple, but in the same spirt that we add an annotation as to enforce the unit as follow:
```python
from typing import Annotated
from pint import Quantity
from infrasys.component import Component
from infrasys.pint_quantities import PydanticPintQuantity
class ACBus(Component):
voltage: Annotated[Quantity, PydanticPintQuantity("volts")]
```
I do not plan to retire the `BaseQuantity` from infrasys, but this could be a simplier solution for people that do not want to create a class that enforces unit validation.
Someone already released this as a package here: https://github.com/tylerh111/pydantic-pint. We do not need the full implementation or dependency since we already had something similar.
> feat: Added `PydanticPintQuantity` as an option to enforce unit validation for fields

- pyproject.toml
- src/infrasys/base_quantity.py
- tests/test_base_quantity.py
It turns out that you can create a `pint.Quantiy` using a numpy type. This PR allows ours custom serialization to cast the numpy types to its python equivalent using `.item()` from numpy.
> fix: Allowing serialization with numpy types inside of `BaseQuantity`

- pyproject.toml
- src/infrasys/serialization.py
Some Pydantic models have computed fields (see example below) that should not be serialized. By default, .model_dump() includes these fields, which can cause deserialization errors since Component does not accept extra arguments. 
The example below shows an example of a computed field that it is only meant to be used at run-time
```python
from infrasys.component import Component
class TestComponent(Component):
a : int
b : int
@computed_field
@property
def sum_a_b(self) -> int:
"""Create attribute that holds the class name."""
return self.a + self.b
```
If we serialize using `TestComponent` using `.model_dump()`, sum_a_b is included, leading to errors when loading JSON. Setting `round_trip=True` in `.model_dump()` ensures computed fields are excluded from serialization.
> feat: Add `round_trip=True` as a default json serialization.

- pyproject.toml
- src/infrasys/cost_curves.py
- src/infrasys/function_data.py
This pr removes the `pint.Quantity` from the field of function data and value curves. We also add a way to supply the units information if needed.
> fix: Removing `pint.Quantity` from linear function data and value curves. 

- src/infrasys/__init__.py
- src/infrasys/arrow_storage.py
- src/infrasys/component_manager.py
- src/infrasys/in_memory_time_series_storage.py
- src/infrasys/location.py
- src/infrasys/pint_quantities.py
- src/infrasys/serialization.py
- src/infrasys/supplemental_attribute.py
- src/infrasys/supplemental_attribute_associations.py
- src/infrasys/supplemental_attribute_manager.py
- src/infrasys/system.py
- src/infrasys/time_series_manager.py
- src/infrasys/time_series_metadata_store.py
- src/infrasys/time_series_models.py
- src/infrasys/utils/sqlite.py
- tests/test_pint_quantities.py
- tests/test_serialization.py
- tests/test_supplemental_attributes.py
- tests/test_system.py
Add support for supplemental attributes, building on work from @jerrypotts.
I added infrastructure for attaching time series to supplemental attributes, but raise an exception if someone tries to do it. We will need to change the time series metadata table schema to fully support it. We already have plans to migrate the schema to match Sienna. I would prefer to do the full migration in one separate PR. @pesap Let me know if you need this functionality immediately and I could make something work.
> Supplemental attributes

- pyproject.toml
- src/infrasys/component_associations.py
This PR creates a new index by `attached_component_uuid` that improves the performance on `list_parent_components`. I also changed the original index to only include `component_uuid`.
Rationale - Both `list_parent_component` and `list_child_component` look for a single uuid at a time and not both. This speed-up search instead of a combined index.
> perf: Improving component association look-up by separating index.

- src/infrasys/arrow_storage.py
- src/infrasys/in_memory_time_series_storage.py
- src/infrasys/time_series_manager.py
- src/infrasys/time_series_metadata_store.py
- src/infrasys/time_series_storage_base.py
- tests/test_in_memory_storage.py
This change will be it easier to convert between time series storage instances. Instead of copying the raw data, it performs a `get_time_series` followed by a `add_time_series`. This will enable full support in chronify.
> Make TimeSeriesStorage.convert_storage more generic

- src/infrasys/component_associations.py
- src/infrasys/system.py
- src/infrasys/utils/classes.py
- tests/test_system.py
- tests/test_utils_classes.py
This change allows callers of list_parent_components and list_child_components to pass abstract component types.
Fixes #70
> feat: Allow abstract types in list_parent_components and list_child_components

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- pyproject.toml
- src/infrasys/chronify_time_series_storage.py
- src/infrasys/id_manager.py
- src/infrasys/system.py
- src/infrasys/time_series_manager.py
- src/infrasys/time_series_metadata_store.py
- src/infrasys/time_series_models.py
- tests/test_in_memory_storage.py
- tests/test_serialization.py
- tests/test_system.py
Chronify is an optional dependency. Users can choose to use it for time series storage. I didn't make it a required dependency in order to minimize our installation. The downside is that developers will have to remember to `pip install -e ".[chronify,dev]"`. I'm open to changing this.
> Add chronify as time series storage option

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- docs/conf.py
- docs/explanation/time_series.md
- pyproject.toml
- src/infrasys/utils/time_utils.py
- tests/test_time_utils.py
This PR adds the capability on infrasys to serialize and deserialize an ISO 8601 duration string. We use both timedelta for miliseconds, seconds, minutes, hours, days, weeks and relativedelta for month, year. I also added some documentation to reflect how users can pass a resolution.
List of changes
---------------
- Two new functions `from_iso_8601` and `to_iso_8601`
- Added 100% coverage for those functions
- Added docs section to reflect how to use the resolution and what we plan to do internally.
> feat: Adding utility scripts to convert resolution as duration specified on the  iso 8601.

- src/infrasys/cost_curves.py
- tests/test_cost_curves.py
Added `startup_fuel_offtake` field to `FuelCurve` class to be compatible with recent change to IS (#89 )
> feat: Add fuel_offtake representation from InfrastructureSystems

- src/infrasys/system.py
- src/infrasys/time_series_manager.py
- src/infrasys/time_series_metadata_store.py
- tests/test_system.py
The current code sets a default value of `time_series_type = SingleTimeSeries` in queries like `System.get_time_series`. This causes problems when the user has other time series types.
This change sets the default to `None` so that queries work with all types.
> Make time series type optional in queries

- src/infrasys/arrow_storage.py
Fixes #105. The root cause of the issue is that the user was de-serializing a system with a read-only time series directory. The infrasys code was unnecessarily copying the directory, which implicitly copied the read-only attribute. This change copies each file or directory inside the source directory (there shouldn't be any directories, only Arrow files).
> Handle read-only source time series directory
